#!/bin/sh

cd ../../..
php artisan migrate:rollback --env=local
php artisan migrate --package=layla/module --env=local
php artisan db:seed --class=Layla\\Module\\Seeds\\ModuleTestDataSeeder --env=local
cd vendor/layla/module
